name: Create PR Artifact

on: pull_request

jobs:
  create_pr_artifact:
    name: Create PR Artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create packages
        run: |
          mkdir bin
          for d in packages/*/ ; do
            (cd "$d" && tgz=$(npm pack) && cp $tgz ../../bin/)
          done
          cd bin
          sha="${{ github.event.pull_request.head.sha }}"
          for f in * ; do
            mv -- "$f" "${f%.tgz}-${sha:0:7}.tgz"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-packages
          path: bin/
          retention-days: 1
